# fly.toml app configuration file generated for fly-demo-binar on 2023-08-07T16:27:23+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fly-demo-binar"
primary_region = "sin"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
