# fly.toml app configuration file generated for quiet-forest-6619 on 2023-08-07T10:55:50+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "quiet-forest-6619"
primary_region = "sin"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
